import {chromium,expect} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {spawn,execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {verifyNativeTrack,verifyNativeUnicodeTrack} from './native-track.mjs';
const out=path.resolve('test-results/browser');await fs.mkdir(out,{recursive:true});
const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'4188'},stdio:['ignore','pipe','pipe']});
await new Promise((ok,no)=>{server.stdout.once('data',ok);server.once('error',no);setTimeout(()=>no(Error('Server startup timed out')),10000).unref();});
let browser;try{browser=await chromium.launch({...(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{}),chromiumSandbox:true,headless:true,args:['--disable-dev-shm-usage']});}catch(error){server.kill();throw error;}
const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true,reducedMotion:'reduce'}),page=await context.newPage();const errors=[],external=[],groups=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>{const u=route.request().url();if(!u.startsWith('http://127.0.0.1:4188')&&!u.startsWith('blob:')&&!u.startsWith('data:')){external.push(u);return route.abort();}return route.continue();});
const group=n=>groups.push(n);const cue=n=>page.locator(`[data-source-number="${n}"]`);const shot=n=>page.screenshot({path:path.join(out,n+'.png'),fullPage:true});const overflow=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal document overflow');
async function example(){await page.locator('#sample').click();await expect(page.locator('#review')).toBeVisible();await expect(page.locator('#build')).toBeDisabled();}
async function decide(){const b=cue(2);await b.locator('select[data-test=decision]').selectOption('split');await expect(b.locator('textarea')).toHaveCount(2);await expect(b.locator('textarea').first()).toHaveValue('');await b.locator('textarea').nth(0).fill('Before');await b.locator('textarea').nth(1).fill('and after');await b.locator('[data-test=save]').click();const d=cue(4);await d.locator('select[data-test=decision]').selectOption('remove');await d.locator('[data-test=save]').click();await expect(page.locator('#build')).toBeEnabled();}
async function download(id,name){const waiting=page.waitForEvent('download');await page.locator(id).click();const d=await waiting;await d.saveAs(path.join(out,name));return fs.readFile(path.join(out,name),'utf8');}
async function print(name){await page.emulateMedia({media:'print'});await page.pdf({path:path.join(out,name+'.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true});await page.emulateMedia({media:'screen'});execFileSync('pdftoppm',['-scale-to','1400','-png',path.join(out,name+'.pdf'),path.join(out,name)]);const text=execFileSync('pdftotext',[path.join(out,name+'.pdf'),'-'],{encoding:'utf8'});assert.ok(text.includes('CaptionSeam'));assert.ok(text.includes('Before'));assert.ok(text.includes('and after'));}
try{
await page.goto('http://127.0.0.1:4188');await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('#review')).toBeHidden();await shot('01-ja-start');group('Japanese initial state with no exports');
await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>location.hash),'#workspace');group('Keyboard skip-to-workspace');
await page.locator('#lang-en').click();await example();await expect(page.locator('#review-count')).toHaveText('2 unresolved');await expect(page.locator('#metric-duration')).toHaveText('14.000 s');await shot('02-en-unresolved');group('Explicit seams and short fragments block export');
const b=cue(2);await b.locator('select[data-test=decision]').focus();await page.keyboard.press('s');await b.locator('select[data-test=decision]').selectOption('split');await b.locator('[data-test=save]').click();await expect(page.locator('#notice')).toContainText('nonempty plain text');await expect(page.locator('#build')).toBeDisabled();group('Blank independently authored split text is rejected');
await decide();await page.locator('#filter-all').click();await expect(page.locator('.cue')).toHaveCount(6);await expect(cue(6).locator('.original-text')).toHaveText('Last\ncaption');await shot('03-en-reviewed');group('Explicit separate texts plus short-cue removal resolve all seams');
await page.locator('#build').click();await expect(page.locator('#downloads')).toBeVisible();for(const [key,name] of [['srt','recut.srt'],['vtt','recut.vtt'],['decisions','decisions.json'],['provenance','provenance.json'],['csv','review.csv']])await download('#download-'+key,name);const srt=await fs.readFile(path.join(out,'recut.srt'),'utf8'),decisions=JSON.parse(await fs.readFile(path.join(out,'decisions.json'),'utf8')),provenance=JSON.parse(await fs.readFile(path.join(out,'provenance.json'),'utf8'));assert.equal(provenance.cues.length,6);assert.equal(provenance.review.length,6);assert.ok(srt.includes('00:00:12,000 --> 00:00:14,000\nLast\ncaption'));assert.match(decisions.sourceHash,/^[0-9a-f]{64}$/);group('Actual browser SRT, VTT, decisions, provenance and CSV downloads');
await print('04-en-print');await page.locator('#lang-ja').click();await expect(page.locator('#build')).toBeEnabled();await expect(page.locator('#downloads')).toBeVisible();await expect(cue(2).locator('textarea').first()).toHaveValue('Before');await shot('05-ja-reviewed');await print('06-ja-print');group('JA/EN switch preserves reviewed texts, exports and A4 print text');
await page.setViewportSize({width:390,height:844});await shot('07-ja-mobile');await overflow();await page.locator('#lang-en').click();await shot('08-en-mobile');await overflow();group('JA/EN 390px responsive layouts');
await page.addStyleTag({content:'body,button,input,textarea,select,p,span,label,strong,h2,h3,summary,a { font-size: 20px !important; }'});await shot('09-en-enlarged-text');await overflow();group('Enlarged text reflow without page overflow');await page.reload();await page.setViewportSize({width:1440,height:1050});await page.locator('#lang-en').click();await example();await decide();await page.locator('#build').click();
await cue(2).locator('textarea').first().fill('Before edited');await expect(page.locator('#downloads')).toBeHidden();await expect(page.locator('#build')).toBeDisabled();await cue(2).locator('[data-test=save]').click();await expect(page.locator('#build')).toBeEnabled();group('Editing reviewed text invalidates its saved decision and all exports');
await page.locator('#decisions-file').setInputFiles(path.join(out,'decisions.json'));await expect(cue(2).locator('textarea').first()).toHaveValue('Before');await page.locator('#build').click();const replay=await download('#download-srt','replayed.srt');assert.equal(replay,srt);group('Exact-input decision replay is byte deterministic');
const changed=JSON.parse(await page.locator('#map-text').inputValue());changed.keep[0].endMs=4900;await page.locator('#map-text').fill(JSON.stringify(changed));await expect(page.locator('#review')).toBeHidden();await expect(page.locator('#downloads')).toBeHidden();await page.locator('#analyze').click();await expect(page.locator('#review')).toBeVisible();await page.locator('#decisions-file').setInputFiles(path.join(out,'decisions.json'));await expect(page.locator('#notice')).toContainText('STALE_DECISIONS');await expect(page.locator('#build')).toBeDisabled();group('Cut-map edits invalidate old decisions and replay rejects stale map hash');
await example();await page.locator('#source-text').fill((await page.locator('#source-text').inputValue()).replace('Welcome','Hello'));await page.locator('#analyze').click();await page.locator('#decisions-file').setInputFiles(path.join(out,'decisions.json'));await expect(page.locator('#notice')).toContainText('STALE_DECISIONS');group('Source edits reject stale decision replay');
await example();await cue(2).locator('select[data-test=decision]').selectOption('fragment');await cue(2).locator('select').nth(1).selectOption('1');await cue(2).locator('textarea').fill('Reviewed fragment');await cue(2).locator('[data-test=save]').click();await expect(cue(2).locator('.status')).toHaveText('Reviewed');await cue(2).locator('[data-test=undo]').click();await expect(cue(2).locator('select[data-test=decision]')).toHaveValue('');await cue(2).locator('select[data-test=decision]').selectOption('continuous');await cue(2).locator('textarea').fill('Reviewed continuous cue');await cue(2).locator('[data-test=save]').click();await expect(cue(2).locator('.status')).toHaveText('Reviewed');group('Keep-one-fragment, continuous-across-cut and clear-decision paths');
await page.locator('#source-file').setInputFiles({name:'invalid.srt',mimeType:'text/plain',buffer:Buffer.from([0xff,0xfe])});await expect(page.locator('#notice')).toContainText('INVALID_UTF8');await expect(page.locator('#review')).toBeHidden();group('Malformed UTF-8 upload cannot retain valid stale review');
const source=await fs.readFile('fixtures/source.srt','utf8'),map=await fs.readFile('fixtures/cut-map.json','utf8');await page.locator('#source-file').setInputFiles({name:'source.srt',mimeType:'text/plain',buffer:Buffer.from(source)});await expect(page.locator('#source-name')).toHaveText('source.srt');await page.locator('#map-file').setInputFiles({name:'cut-map.json',mimeType:'application/json',buffer:Buffer.from(map)});await expect(page.locator('#map-name')).toHaveText('cut-map.json');await page.locator('#analyze').click();await expect(page.locator('#review-count')).toHaveText('2 unresolved');group('Actual source SRT and cut-map file inputs');
await page.locator('#source-text').fill('1\n00:00:01,000 --> 00:00:02,000\n<b>tag</b>');await page.locator('#analyze').click();await expect(page.locator('#notice')).toContainText('PLAIN_TEXT_REQUIRED');await expect(page.locator('#review')).toBeHidden();group('Unsupported markup rejected before review');
await example();await page.locator('#map-text').fill('{"version":1,"keep":[{"startMs":8000,"endMs":12000},{"startMs":0,"endMs":5000}]}');await page.locator('#analyze').click();await expect(page.locator('#notice')).toContainText('KEEP_RANGES_OVERLAP_OR_UNSORTED');group('Reordered source cuts cannot be silently accepted');
await page.evaluate(()=>{window.__original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){const result=await window.__original.call(this);if(this.name.startsWith('slow'))await new Promise(r=>setTimeout(r,450));return result;};});await page.locator('#source-file').setInputFiles({name:'slow-reset.srt',mimeType:'text/plain',buffer:Buffer.from(source)});await page.locator('#reset').click();await page.waitForTimeout(600);await expect(page.locator('#source-text')).toHaveValue('');await expect(page.locator('#review')).toBeHidden();group('Reset wins over an in-flight source read');
await page.locator('#source-file').setInputFiles({name:'slow-old.srt',mimeType:'text/plain',buffer:Buffer.from(source)});await page.locator('#source-file').setInputFiles({name:'newer.srt',mimeType:'text/plain',buffer:Buffer.from(source.replace('Welcome','Newest'))});await expect(page.locator('#source-name')).toHaveText('newer.srt');await page.waitForTimeout(600);assert.ok((await page.locator('#source-text').inputValue()).includes('Newest'));group('Newer file selection wins over a late old source read');
await page.locator('#source-file').setInputFiles({name:'slow-cross-source.srt',mimeType:'text/plain',buffer:Buffer.from(source)});await page.locator('#map-file').setInputFiles({name:'fast-cross-map.json',mimeType:'application/json',buffer:Buffer.from(map)});await expect(page.locator('#analyze')).toBeDisabled();await page.waitForTimeout(600);await expect(page.locator('#source-name')).toHaveText('slow-cross-source.srt');await expect(page.locator('#map-name')).toHaveText('fast-cross-map.json');await expect(page.locator('#analyze')).toBeEnabled();group('Slow source and fast map reads both survive independent upload');
await page.locator('#map-file').setInputFiles({name:'slow-cross-map.json',mimeType:'application/json',buffer:Buffer.from(map)});await page.locator('#source-file').setInputFiles({name:'fast-cross-source.srt',mimeType:'text/plain',buffer:Buffer.from(source)});await expect(page.locator('#analyze')).toBeDisabled();await page.waitForTimeout(600);await expect(page.locator('#map-name')).toHaveText('slow-cross-map.json');await expect(page.locator('#source-name')).toHaveText('fast-cross-source.srt');await expect(page.locator('#analyze')).toBeEnabled();group('Slow map and fast source reads both survive independent upload');
await example();await decide();await page.locator('#decisions-file').setInputFiles({name:'slow-decisions.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(decisions))});await cue(2).locator('textarea').first().fill('Newest decision text');await page.waitForTimeout(600);await expect(cue(2).locator('textarea').first()).toHaveValue('Newest decision text');await expect(page.locator('#build')).toBeDisabled();group('Typing a newer decision prevents slow replay from restoring stale text');
await page.evaluate(()=>{File.prototype.arrayBuffer=window.__original;});await page.locator('#reset').click();await expect(page.locator('#source-text')).toHaveValue('');await expect(page.locator('#map-text')).toHaveValue('');await expect(page.locator('#review')).toBeHidden();await expect(page.locator('#downloads')).toBeHidden();group('Reset clears all inputs, decisions and downloads');
await page.locator('#source-text').fill('1\n00:00:01,000 --> 00:00:03,000\nようこそ 🎬 &amp; & literal\n字幕を残す');await page.locator('#map-text').fill('{"version":1,"keep":[{"startMs":0,"endMs":14000}]}');await page.locator('#analyze').click();await expect(page.locator('#build')).toBeEnabled();await page.locator('#build').click();await download('#download-vtt','unicode.vtt');group('Actual Unicode, literal entity and multiline WebVTT download');
// Local file distribution must execute without HTTP or a build toolchain.
const filePage=await context.newPage();await filePage.goto('file://'+path.resolve('dist/index.html'));await filePage.locator('#lang-en').click();await filePage.locator('#sample').click();await expect(filePage.locator('#review-count')).toHaveText('2 unresolved');await filePage.close();group('Standalone HTML works from file://');
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);group('No page errors or external requests during the app workflow');
// No trace is captured: native test video must never leak into publication artifacts.
await page.unroute('**/*');await verifyNativeTrack(page,path.join(out,'recut.vtt'),{outputDir:out});group('Actual exported VTT consumed through native HTML track and 34 boundary samples');await verifyNativeUnicodeTrack(page,path.join(out,'unicode.vtt'),{outputDir:out});group('Actual Unicode, ampersand entity and multiline text preserved by native WebVTT rendering');
const actualDownloads=await Promise.all(['recut.srt','recut.vtt','decisions.json','provenance.json','review.csv'].map(async name=>({name,sha256:createHash('sha256').update(await fs.readFile(path.join(out,name))).digest('hex')})));const summary={actualDownloads,status:'pass',browserVersion:browser.version(),chromiumSandbox:true,groupCount:groups.length,groups,errors,externalRequests:external};await fs.writeFile(path.join(out,'results.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify(summary));
}catch(error){await fs.writeFile(path.join(out,'failure.json'),JSON.stringify({status:'fail',groups,error:error.stack,errors,externalRequests:external},null,2)+'\n');await shot('failure').catch(()=>{});throw error;}finally{await browser.close();server.kill();}
