import test from 'node:test';import assert from 'node:assert/strict';import {analyze,emptyDecisions,exportBundle,parseSrt,validateText,decodeUtf8,parseCutMap,validateDecisions} from '../src/core.mjs';
const map={version:1,keep:[{startMs:0,endMs:20000}]};
test('untouched visible spacing and literal ampersand entities remain authored text',async()=>{const source='1\n00:00:01,000 --> 00:00:02,000\n  keep &amp; this  \n';const plan=await analyze(source,map);const e=exportBundle(plan,emptyDecisions(plan));assert.equal(e.result.cues[0].text,'  keep &amp; this  ');assert.ok(e.vtt.includes('  keep &amp;amp; this  '));assert.equal(parseSrt(e.srt)[0].text,'  keep &amp; this  ');});
test('outer payload newlines cannot produce empty cue separator injection',()=>{for(const s of ['\ntext','text\n','one\r\rtwo','one\r\n\r\ntwo'])assert.throws(()=>validateText(s));});
test('fatal UTF8 rejects corrupted bytes and accepts own unicode fixture',()=>{assert.throws(()=>decodeUtf8(new Uint8Array([0xff,0xfe])));assert.equal(decodeUtf8(new TextEncoder().encode('字幕🎬')),'字幕🎬');});
test('same source ordinal has content-bound cue identity',async()=>{const a=await analyze('9\n00:00:01,000 --> 00:00:02,000\nA',map),b=await analyze('9\n00:00:01,000 --> 00:00:02,000\nB',map);assert.notEqual(a.rows[0].id,b.rows[0].id);assert.match(a.rows[0].id,/^c0001-[a-f0-9]{12}$/);});
test('all contract objects reject extra playback speed or mixed source fields',()=>{assert.throws(()=>parseCutMap({...map,speed:2}));assert.throws(()=>parseCutMap({version:1,keep:[{startMs:0,endMs:1000,source:'another'}]}));});

test('legacy ASS styling and newline escapes are rejected instead of interpreted by SRT consumers',()=>{for(const text of [String.raw`{\an8}top`,String.raw`a\Nb`,String.raw`a\nb`,String.raw`a\hb`])assert.throws(()=>validateText(text));});

test('unpaired surrogates cannot silently become replacement characters in downloaded UTF-8',()=>{for(const value of ['A\ud800B','A\udc00B'])assert.throws(()=>validateText(value));assert.equal(validateText('字幕🎬'),'字幕🎬');});
test('every accepted pretty-printed decision export fits the replay byte cap',async()=>{const source='1\n00:00:00,000 --> 00:05:00,000\nOriginal';const keep=Array.from({length:300},(_,i)=>({startMs:i*1000,endMs:i*1000+600}));const plan=await analyze(source,{version:1,keep}),bundle=emptyDecisions(plan);bundle.decisions[plan.rows[0].id]={action:'split',texts:keep.map(()=>'字'.repeat(9999))};assert.throws(()=>validateDecisions(plan,bundle),{code:'DECISION_SIZE_LIMIT'});assert.throws(()=>exportBundle(plan,bundle),{code:'DECISION_SIZE_LIMIT'});});
