import test from 'node:test';import assert from 'node:assert/strict';import {assertBoundarySample,EXPECTED_NATIVE_CUES as cues} from './native-track.mjs';
const pos=(time,side='exact')=>({time,side});
test('native harness keeps strict start-inclusive end-exclusive checks away from boundaries',()=>{assert.doesNotThrow(()=>assertBoundarySample({cues:[cues[0]]},pos(2.99,'before')));assert.doesNotThrow(()=>assertBoundarySample({cues:[]},pos(3.01,'after')));assert.throws(()=>assertBoundarySample({cues:[cues[0]]},pos(3.01,'after')));assert.throws(()=>assertBoundarySample({cues:[]},pos(2.99,'before')));});
test('exact endpoint retains spec expectation and explicitly labels the native discrepancy',()=>{assert.equal(assertBoundarySample({cues:[]},pos(3)).matchesHalfOpenSpec,true);const observed=assertBoundarySample({cues:[cues[0]]},pos(3));assert.equal(observed.matchesHalfOpenSpec,false);assert.deepEqual(observed.specExpected,[]);assert.equal(observed.endpointModel,'native-end-inclusive-discrepancy');});
test('exact downloaded cue state must equal independent positive control, not just either valid model',()=>{assert.doesNotThrow(()=>assertBoundarySample({cues:[cues[0]]},pos(3),{cues:[cues[0]]}));assert.throws(()=>assertBoundarySample({cues:[]},pos(3),{cues:[cues[0]]}));assert.throws(()=>assertBoundarySample({cues:[cues[0]]},pos(3),{cues:[]}));});
test('adjacent exact endpoint cannot lose the newly starting cue or add unrelated cues',()=>{assert.doesNotThrow(()=>assertBoundarySample({cues:[cues[2]]},pos(5)));assert.doesNotThrow(()=>assertBoundarySample({cues:[cues[1],cues[2]]},pos(5)));assert.throws(()=>assertBoundarySample({cues:[cues[1]]},pos(5)));assert.throws(()=>assertBoundarySample({cues:[cues[0],cues[2]]},pos(5)));});

import {assertPlaybackProgression} from './native-track.mjs';
function syntheticObservation(){return {playbackRate:1,ended:true,duration:14.25,rateChanges:[],samples:Array.from({length:1426},(_,i)=>{const time=i/100;return {time,rate:1,cues:cues.filter(c=>c.start<=time&&time<c.end)};}),cueEvents:cues.flatMap(c=>[{...c,type:'enter',time:c.start+.001},{...c,type:'exit',time:c.end+.001}]),cueChanges:[1,3,4,5,6,7,8,10,11,12,14].map(time=>({time:time+.001,cues:[]}))};}
test('playback checker accepts complete 1x native-observation-shaped evidence',()=>assert.equal(assertPlaybackProgression(syntheticObservation()).status,'pass'));
test('playback checker rejects wrong active text away from a boundary',()=>{const data=syntheticObservation();data.samples[200].cues=[];assert.throws(()=>assertPlaybackProgression(data));});
test('playback checker rejects missing, duplicate or late cue events',()=>{for(const mutate of [d=>d.cueEvents.pop(),d=>d.cueEvents.push(d.cueEvents[0]),d=>d.cueEvents[0].time=1.3]){const data=syntheticObservation();mutate(data);assert.throws(()=>assertPlaybackProgression(data));}});
test('playback checker rejects missing cuechange evidence or insufficient boundary sampling',()=>{const data=syntheticObservation();data.cueChanges=[];assert.throws(()=>assertPlaybackProgression(data));const sparse=syntheticObservation();sparse.samples=sparse.samples.filter(s=>s.time<2.5||s.time>3.5);assert.throws(()=>assertPlaybackProgression(sparse));});
test('playback checker rejects speed changes and unfinished playback',()=>{for(const mutate of [d=>d.playbackRate=2,d=>d.ended=false]){const data=syntheticObservation();mutate(data);assert.throws(()=>assertPlaybackProgression(data));}});

test('playback checker rejects nonfinite/negative media times and observed transient rate changes',()=>{for(const mutate of [d=>d.samples[200].time=NaN,d=>d.samples[200].time=-1,d=>d.cueEvents[0].time=NaN,d=>d.cueChanges[0].time=Infinity,d=>d.rateChanges.push({time:2,rate:2}),d=>d.samples[200].rate=2]){const data=syntheticObservation();mutate(data);assert.throws(()=>assertPlaybackProgression(data));}});
