/** Adversarial contracts independent of the app's own example fixtures. */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {analyze, decodeUtf8, emptyDecisions, exportBundle, parseCutMap, parseSrt,
  resolve, validateDecisions, validateText} from '../src/core.mjs';

const fixture = JSON.parse(fs.readFileSync(new URL('./fixtures/hand_expected.json', import.meta.url)));
const mapOf = keep => ({version: 1, keep: keep.map(([startMs,endMs]) => ({startMs,endMs}))});
const map = mapOf(fixture.keep);
const clock = ms => `${String(Math.floor(ms / 3600000)).padStart(2,'0')}:${String(Math.floor(ms / 60000) % 60).padStart(2,'0')}:${String(Math.floor(ms / 1000) % 60).padStart(2,'0')},${String(ms % 1000).padStart(3,'0')}`;
const sourceOf = cues => cues.map((c,i) => `${7 + i * 7}\n${clock(c.startMs)} --> ${clock(c.endMs)}\n${c.text}\n`).join('\n');
const source = sourceOf(fixture.source);
const one = (start, end, text = 'Text') => sourceOf([{startMs:start,endMs:end,text}]);
const codeIs = code => error => error?.code === code;
const fresh = async () => {
  const plan = await analyze(source, map);
  const decisions = emptyDecisions(plan);
  decisions.decisions[plan.rows[1].id] = {action:'split',texts:['Before','and after']};
  decisions.decisions[plan.rows[3].id] = {action:'remove'};
  return {plan,decisions};
};

// Exactly known numbers, rather than an output snapshot generated by core.mjs.
test('hand-calculated export has six newly numbered, nonoverlapping cues and exact multiline text', async () => {
  const {plan,decisions} = await fresh();
  const bundle = exportBundle(plan,decisions);
  assert.equal(plan.durationMs,14000);
  assert.deepEqual(bundle.result.cues.map(({number,startMs,endMs,text}) => ({number,startMs,endMs,text})), fixture.output);
  assert.equal(bundle.srt.replace(/\n+$/,''),fixture.srt.replace(/\n+$/,''));
  assert.deepEqual(parseSrt(bundle.srt).map(c => c.sourceNumber),[1,2,3,4,5,6]);
  assert.deepEqual(plan.rows.map(c => c.sourceNumber),[7,14,21,28,35,42]);
  assert.equal(bundle.result.cues.at(-1).text,'Last\ncaption');
  assert.equal(bundle.result.receipt.length,6);
  const removed = bundle.result.receipt[3];
  assert.equal(removed.originalText,'Across a tiny seam');
  assert.deepEqual(removed.outputNumbers,[]);
  assert.deepEqual(removed.decision,{action:'remove'});
});

test('unreviewed cut and tiny fragments block export instead of inferring words', async () => {
  const {plan} = await fresh();
  const decisions = emptyDecisions(plan);
  assert.deepEqual(resolve(plan,decisions).unresolved,[plan.rows[1].id,plan.rows[3].id]);
  assert.throws(() => exportBundle(plan,decisions),codeIs('UNRESOLVED_CUES'));
  decisions.decisions[plan.rows[1].id] = {action:'split',texts:['Before','and after']};
  assert.throws(() => exportBundle(plan,decisions),codeIs('UNRESOLVED_CUES'));
  assert.deepEqual(plan.rows[3].reasons,['clipped','split','short']);
});

test('explicit fragment and continuous decisions produce their exact chosen text', async () => {
  const {plan,decisions} = await fresh();
  decisions.decisions[plan.rows[1].id] = {action:'fragment',fragmentIndex:1,text:'Explicit later words'};
  let cues = exportBundle(plan,decisions).result.cues;
  assert.deepEqual([cues[1].startMs,cues[1].endMs,cues[1].text],[5000,6000,'Explicit later words']);
  decisions.decisions[plan.rows[1].id] = {action:'continuous',text:'Explicit continuity & seam'};
  const bundle = exportBundle(plan,decisions);
  cues = bundle.result.cues;
  assert.deepEqual([cues[1].startMs,cues[1].endMs,cues[1].text],[4000,6000,'Explicit continuity & seam']);
  assert.equal(cues[1].sourceIntervals.length,2);
  assert.match(bundle.vtt,/Explicit continuity &amp; seam/);
});

test('wholly removed sources have receipts but cannot create an empty SRT export', async () => {
  const plan = await analyze(one(5000,8000),map);
  const decisions = emptyDecisions(plan);
  const resolved = resolve(plan,decisions);
  assert.equal(plan.rows[0].status,'removed');
  assert.deepEqual(resolved.cues,[]);
  assert.deepEqual(resolved.unresolved,[]);
  assert.equal(resolved.receipt[0].originalText,'Text');
  assert.deepEqual(resolved.receipt[0].outputNumbers,[]);
  assert.throws(() => exportBundle(plan,decisions),codeIs('EMPTY_EXPORT'));
});

test('499ms requires a decision; 500ms is retained automatically', async () => {
  for (const [length,status] of [[1,'review'],[499,'review'],[500,'automatic'],[501,'automatic']]) {
    const plan = await analyze(one(0,length),mapOf([[0,1000]]));
    assert.equal(plan.rows[0].status,status);
    const decisions = emptyDecisions(plan);
    if (status === 'review') {
      assert.throws(() => exportBundle(plan,decisions),codeIs('UNRESOLVED_CUES'));
      decisions.decisions[plan.rows[0].id] = {action:'fragment',fragmentIndex:0,text:'Explicit short cue'};
    }
    assert.equal(exportBundle(plan,decisions).result.cues[0].endMs,length);
  }
});

test('touching ranges coalesce but zero-duration boundary intersections are discarded', async () => {
  const spanning = await analyze(one(1000,9000),mapOf([[0,5000],[5000,10000]]));
  assert.equal(spanning.rows[0].status,'automatic');
  assert.equal(spanning.rows[0].fragments.length,1);
  assert.deepEqual(spanning.rows[0].fragments[0].rangeIndexes,[0,1]);
  const plan = await analyze(one(4999,8001),map);
  assert.deepEqual(plan.rows[0].fragments.map(f => [f.sourceStartMs,f.sourceEndMs,f.outputStartMs,f.outputEndMs]),
    [[4999,5000,4999,5000],[8000,8001,5000,5001]]);
  for (const [start,end] of [[5000,8000],[12000,15000],[20000,21000]]) {
    const removed = await analyze(one(start,end),map);
    assert.equal(removed.rows[0].status,'removed');
  }
});

test('stale decisions are rejected for every binding field and changed source bytes', async () => {
  const {plan,decisions} = await fresh();
  for (const field of ['sourceHash','cutMapHash','basisHash','minFragmentMs']) {
    const stale = structuredClone(decisions);
    stale[field] = field === 'minFragmentMs' ? 499 : '0'.repeat(64);
    assert.throws(() => exportBundle(plan,stale),codeIs('STALE_DECISIONS'),field);
  }
  for (const changedSource of [source.replace('Welcome','Different words'),source + '\n',source.replaceAll('\n','\r\n')]) {
    const changed = await analyze(changedSource,map);
    assert.throws(() => exportBundle(changed,decisions),codeIs('STALE_DECISIONS'));
  }
});

test('changed cut maps invalidate decisions, including a geometrically equivalent partition', async () => {
  const {decisions} = await fresh();
  for (const changedMap of [mapOf([[0,4999],[8000,12000],[15000,20000]]),
    mapOf([[0,2000],[2000,5000],[8000,12000],[15000,20000]])]) {
    const changed = await analyze(source,changedMap);
    assert.throws(() => exportBundle(changed,decisions),codeIs('STALE_DECISIONS'));
  }
});

test('unknown, removed and automatic decision targets are rejected', async () => {
  const {plan,decisions} = await fresh();
  for (const id of ['not-a-source-cue',plan.rows[0].id]) {
    const bundle = structuredClone(decisions);
    bundle.decisions[id] = {action:'remove'};
    assert.throws(() => validateDecisions(plan,bundle),codeIs('DECISION_TARGET_INVALID'));
  }
  const removed = await analyze(one(5000,8000),map);
  const bundle = emptyDecisions(removed);
  bundle.decisions[removed.rows[0].id] = {action:'remove'};
  assert.throws(() => validateDecisions(removed,bundle),codeIs('DECISION_TARGET_INVALID'));
});

test('malformed review actions and missing independently written fragment text are rejected', async () => {
  const {plan,decisions} = await fresh();
  const invalid = [
    {}, {action:'guess'}, {action:'remove',text:'not allowed'},
    {action:'fragment',fragmentIndex:-1,text:'words'}, {action:'fragment',fragmentIndex:2,text:'words'},
    {action:'fragment',fragmentIndex:0.5,text:'words'}, {action:'fragment',fragmentIndex:'0',text:'words'},
    {action:'fragment',fragmentIndex:0}, {action:'fragment',fragmentIndex:0,text:'words',texts:[]},
    {action:'split',texts:['one']}, {action:'split',texts:['one','two','three']},
    {action:'split',texts:['one','']}, {action:'split',texts:['one','two'],text:'ambiguous'},
    {action:'continuous'}, {action:'continuous',text:'words',fragmentIndex:0},
    {action:'continuous',text:'words',extra:'unknown'},
  ];
  for (const decision of invalid) {
    const bundle = structuredClone(decisions);
    bundle.decisions[plan.rows[1].id] = decision;
    assert.throws(() => exportBundle(plan,bundle),undefined,JSON.stringify(decision));
  }
  const clipped = await analyze(one(4000,6000),map);
  for (const decision of [{action:'split',texts:['one']},{action:'continuous',text:'words'}]) {
    const bundle = emptyDecisions(clipped);
    bundle.decisions[clipped.rows[0].id] = decision;
    assert.throws(() => exportBundle(clipped,bundle));
  }
});

test('blank lines introduced by CR normalization cannot escape text validation', () => {
  for (const text of ['one\r\rtwo','one\r \rtwo','one\r\n\r\ntwo','one\n\ntwo']) {
    assert.throws(() => validateText(text),codeIs('PLAIN_TEXT_REQUIRED'),JSON.stringify(text));
  }
  assert.equal(validateText('one\r\ntwo'),'one\ntwo');
});

test('unsafe or unsupported subtitle text cannot become export blocks or markup', () => {
  for (const text of ['', '   ', '<b>words</b>', 'a --> b', 'one\u0000two', 'one\u001ftwo', 'one\u007ftwo']) {
    assert.throws(() => validateText(text),codeIs('PLAIN_TEXT_REQUIRED'),JSON.stringify(text));
  }
  assert.equal(validateText('日本語 🪡\nSecond line & literal ampersand'),'日本語 🪡\nSecond line & literal ampersand');
});

test('malformed, overlapping and unsorted SRT blocks fail before composition', () => {
  const invalid = [
    ['', 'EMPTY_SOURCE'],
    ['1\n00:00:01,000 --> 00:00:01,000\nZero\n','NONPOSITIVE_CUE'],
    ['1\n00:00:02,000 --> 00:00:01,000\nReverse\n','NONPOSITIVE_CUE'],
    ['1\n00:00:00.000 --> 00:00:01.000\nDots\n','SRT_TIMING_REQUIRED'],
    ['1\n00:60:00,000 --> 01:01:00,000\nMinute\n','INVALID_TIMESTAMP'],
    ['1\n25:00:00,000 --> 26:00:00,000\nLong\n','TIME_LIMIT'],
    [one(0,2000) + '\n' + one(1000,3000).replace(/^7\n/,'14\n'),'SOURCE_CUES_OVERLAP_OR_UNSORTED'],
    [one(2000,3000) + '\n' + one(0,1000).replace(/^7\n/,'14\n'),'SOURCE_CUES_OVERLAP_OR_UNSORTED'],
    [one(0,1000) + '\n' + one(2000,3000),'INVALID_CUE_NUMBER'],
    ['0\n00:00:00,000 --> 00:00:01,000\nZero number\n','INVALID_CUE_NUMBER'],
    ['1\n00:00:00,000 --> 00:00:01,000 position:10%\nExtended\n','SRT_TIMING_REQUIRED'],
    [one(0,1000,'\ufffd'),'INVALID_UTF8'],
  ];
  for (const [text,code] of invalid) assert.throws(() => parseSrt(text),codeIs(code),code);
});

test('BOM, CRLF, nonconsecutive numbering and actual UTF-8 survive parsing', () => {
  const srt = '\ufeff' + source.replaceAll('\n','\r\n');
  const cues = parseSrt(srt);
  assert.equal(cues.length,6);
  assert.equal(cues.at(-1).text,'Last\ncaption');
  assert.equal(decodeUtf8(new TextEncoder().encode('日本語 🪡')),'日本語 🪡');
  assert.throws(() => decodeUtf8(Uint8Array.from([0xc3,0x28])),codeIs('INVALID_UTF8'));
});

test('cut-map schema is strict about type, ordering, intervals and unsupported edit semantics', () => {
  const invalid = [null,[],{}, {version:2,keep:[{startMs:0,endMs:1000}]},
    {version:1,keep:[]}, {version:1,keep:[{startMs:0,endMs:1000,speed:2}]},
    {version:1,keep:[{startMs:0,endMs:1000}],tracks:[]},
    ...[[[0,0]],[[2,1]],[[-1,2]],[[0,1.5]],[[false,1000]],[[0,NaN]],[[0,Infinity]],
      [[0,'1000']],[[0,Number.MAX_SAFE_INTEGER]],[[0,86400001]],[[0,2000],[1000,3000]],[[2000,3000],[0,1000]]].map(mapOf),
  ];
  for (const bad of invalid) assert.throws(() => parseCutMap(bad),undefined,JSON.stringify(bad));
  assert.throws(() => parseCutMap('{bad json'),codeIs('INVALID_CUT_MAP_JSON'));
  assert.deepEqual(parseCutMap(JSON.stringify(map)),map);
});

test('CSV escapes formula-like source text; provenance preserves the removed fragments', async () => {
  const plan = await analyze(one(0,1000,'=SUM(1,2)') + '\n' + one(5000,8000,'@removed').replace(/^7\n/,'14\n'),map);
  const bundle = exportBundle(plan,emptyDecisions(plan));
  assert.match(bundle.csv,/"'=SUM\(1,2\)"/);
  assert.match(bundle.csv,/"'@removed"/);
  const provenance = JSON.parse(bundle.provenance);
  assert.equal(provenance.sourceHash,plan.sourceHash);
  assert.deepEqual(provenance.cutMap,map);
  assert.equal(provenance.review[1].status,'removed');
  assert.deepEqual(provenance.review[1].outputNumbers,[]);
});

test('export and JSON round-trip do not mutate source plans or review decisions', async () => {
  const {plan,decisions} = await fresh();
  const before = JSON.stringify({plan,decisions});
  const first = exportBundle(plan,decisions);
  const second = exportBundle(plan,JSON.parse(first.decisions));
  assert.equal(first.srt,second.srt);
  assert.equal(first.provenance,second.provenance);
  assert.equal(JSON.stringify({plan,decisions}),before);
});
