// CaptionSeam: integer millisecond, single-source, 1x interval composition.
export const VERSION='caption-seam/v1';
export const MIN_FRAGMENT_MS=500;
export const LIMITS=Object.freeze({bytes:2_000_000,decisionBytes:8_000_000,cues:5000,ranges:500,cueText:10000,timeMs:86_400_000});
export class CaptionError extends Error {constructor(code,detail=''){super(detail?`${code}: ${detail}`:code);this.code=code;}}
const fail=(code,detail)=>{throw new CaptionError(code,detail);};
const integer=n=>Number.isSafeInteger(n)&&n>=0&&n<=LIMITS.timeMs;
const object=o=>o!==null&&typeof o==='object'&&!Array.isArray(o);
function keys(o,allowed){if(!object(o)||Object.keys(o).some(k=>!allowed.includes(k)))fail('UNSUPPORTED_FIELDS');}
export function decodeUtf8(buffer){try{return new TextDecoder('utf-8',{fatal:true}).decode(buffer);}catch{fail('INVALID_UTF8');}}
export function validateText(text){if(typeof text==='string')text=text.replaceAll('\r\n','\n').replaceAll('\r','\n');if(typeof text!=='string'||!text.isWellFormed()||!text.trim()||text.length>LIMITS.cueText||/[<>\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/u.test(text)||(/\n\s*\n/.test(text)||text.startsWith('\n')||text.endsWith('\n'))||text.includes('-->')||text.includes('{\\')||/\\[Nnh]/.test(text))fail('PLAIN_TEXT_REQUIRED');return text;}
export function parseTime(s){const m=/^(\d{2}):(\d{2}):(\d{2}),(\d{3})$/.exec(s);if(!m||+m[2]>59||+m[3]>59)fail('INVALID_TIMESTAMP',s);const t=((+m[1]*60+ +m[2])*60+ +m[3])*1000+ +m[4];if(!integer(t))fail('TIME_LIMIT');return t;}
export function stamp(ms,vtt=false){if(!integer(ms))fail('INVALID_TIME');return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}${vtt?'.':','}${String(ms%1000).padStart(3,'0')}`;}
export function parseSrt(raw){if(typeof raw!=='string'||new TextEncoder().encode(raw).length>LIMITS.bytes)fail('SOURCE_SIZE_LIMIT');if(raw.includes('\uFFFD'))fail('INVALID_UTF8');const text=raw.replace(/^\uFEFF/,'').replaceAll('\r\n','\n').replaceAll('\r','\n').replace(/^\n+|\n+$/g,'');if(!text.trim())fail('EMPTY_SOURCE');const blocks=text.split(/\n[\t ]*\n+/);if(blocks.length>LIMITS.cues)fail('CUE_LIMIT');let lastEnd=0;const used=new Set();return blocks.map((block,i)=>{const lines=block.split('\n');if(lines.length<3||!/^\d+$/.test(lines[0])||!Number.isSafeInteger(+lines[0])||+lines[0]<1||used.has(+lines[0]))fail('INVALID_CUE_NUMBER',`${i+1}`);used.add(+lines[0]);const m=/^(\d{2}:\d{2}:\d{2},\d{3}) --> (\d{2}:\d{2}:\d{2},\d{3})$/.exec(lines[1]);if(!m)fail('SRT_TIMING_REQUIRED',`${i+1}`);const startMs=parseTime(m[1]),endMs=parseTime(m[2]);if(endMs<=startMs)fail('NONPOSITIVE_CUE',`${i+1}`);if(startMs<lastEnd)fail('SOURCE_CUES_OVERLAP_OR_UNSORTED',`${i+1}`);lastEnd=endMs;return {id:`c${String(i+1).padStart(4,'0')}`,sourceNumber:+lines[0],startMs,endMs,text:validateText(lines.slice(2).join('\n'))};});}
export function parseCutMap(input){let map=input;if(typeof input==='string'){if(input.length>100000)fail('CUT_MAP_SIZE_LIMIT');try{map=JSON.parse(input);}catch{fail('INVALID_CUT_MAP_JSON');}}keys(map,['version','keep']);if(map.version!==1||!Array.isArray(map.keep)||!map.keep.length||map.keep.length>LIMITS.ranges)fail('CUT_MAP_SCHEMA');let end=-1;const keep=map.keep.map(r=>{keys(r,['startMs','endMs']);if(!integer(r.startMs)||!integer(r.endMs)||r.endMs<=r.startMs)fail('INVALID_KEEP_RANGE');if(r.startMs<end)fail('KEEP_RANGES_OVERLAP_OR_UNSORTED');end=r.endMs;return {startMs:r.startMs,endMs:r.endMs};});return {version:1,keep};}
export async function sha256(text){const data=typeof text==='string'?new TextEncoder().encode(text):text;return [...new Uint8Array(await crypto.subtle.digest('SHA-256',data))].map(b=>b.toString(16).padStart(2,'0')).join('');}
function coalesce(keep){const out=[];for(let i=0;i<keep.length;i++){const r=keep[i],p=out.at(-1);if(p&&p.endMs===r.startMs){p.endMs=r.endMs;p.rangeIndexes.push(i);}else out.push({...r,rangeIndexes:[i]});}let elapsed=0;return out.map(r=>{const result={...r,outputStartMs:elapsed};elapsed+=r.endMs-r.startMs;return result;});}
export async function analyze(source,cutMap){const cues=parseSrt(source),map=parseCutMap(cutMap),ranges=coalesce(map.keep),sourceHash=await sha256(source),cutMapHash=await sha256(JSON.stringify(map)),basisHash=await sha256(`${VERSION}\n${sourceHash}\n${cutMapHash}\n${MIN_FRAGMENT_MS}`);for(const cue of cues){cue.textHash=await sha256(cue.text);cue.id+=`-${(await sha256(JSON.stringify(cue))).slice(0,12)}`;}const rows=cues.map(cue=>{const fragments=[];for(const r of ranges){const s=Math.max(cue.startMs,r.startMs),e=Math.min(cue.endMs,r.endMs);if(e>s)fragments.push({sourceStartMs:s,sourceEndMs:e,outputStartMs:r.outputStartMs+s-r.startMs,outputEndMs:r.outputStartMs+e-r.startMs,rangeIndexes:r.rangeIndexes});}const retained=fragments.reduce((n,f)=>n+f.sourceEndMs-f.sourceStartMs,0);const reasons=[];if(retained&&retained<cue.endMs-cue.startMs)reasons.push('clipped');if(fragments.length>1)reasons.push('split');if(fragments.some(f=>f.outputEndMs-f.outputStartMs<MIN_FRAGMENT_MS))reasons.push('short');return {...cue,fragments,reasons,status:!fragments.length?'removed':reasons.length?'review':'automatic'};});return {version:VERSION,sourceHash,cutMapHash,basisHash,minFragmentMs:MIN_FRAGMENT_MS,map,rows,durationMs:ranges.reduce((n,r)=>n+r.endMs-r.startMs,0)};}
function decisionContext(plan){return {cutMap:plan.map,cues:plan.rows.map(r=>({id:r.id,sourceNumber:r.sourceNumber,sourceStartMs:r.startMs,sourceEndMs:r.endMs,originalText:r.text,textHash:r.textHash,fragments:r.fragments}))};}
export function emptyDecisions(plan){return {schema:'caption-seam-decisions/v1',sourceHash:plan.sourceHash,cutMapHash:plan.cutMapHash,basisHash:plan.basisHash,minFragmentMs:MIN_FRAGMENT_MS,context:decisionContext(plan),decisions:{}};}
export function validateDecisions(plan,bundle){if(new TextEncoder().encode(JSON.stringify(bundle,null,2)+'\n').length>LIMITS.decisionBytes)fail('DECISION_SIZE_LIMIT');keys(bundle,['schema','sourceHash','cutMapHash','basisHash','minFragmentMs','context','decisions']);if(bundle.schema!=='caption-seam-decisions/v1'||bundle.sourceHash!==plan.sourceHash||bundle.cutMapHash!==plan.cutMapHash||bundle.basisHash!==plan.basisHash||bundle.minFragmentMs!==MIN_FRAGMENT_MS)fail('STALE_DECISIONS');if(JSON.stringify(bundle.context)!==JSON.stringify(decisionContext(plan)))fail('STALE_DECISION_CONTEXT');if(!object(bundle.decisions))fail('INVALID_DECISIONS');for(const [id,d] of Object.entries(bundle.decisions)){const row=plan.rows.find(r=>r.id===id);if(!row||row.status!=='review')fail('DECISION_TARGET_INVALID',id);keys(d,['action','fragmentIndex','text','texts']);if(d.action==='remove'){if(Object.keys(d).length!==1)fail('INVALID_REMOVE_DECISION');}else if(d.action==='fragment'){if(!Number.isInteger(d.fragmentIndex)||!row.fragments[d.fragmentIndex]||Object.hasOwn(d,'texts'))fail('INVALID_FRAGMENT_DECISION');validateText(d.text);}else if(d.action==='split'){if(row.fragments.length<2||!Array.isArray(d.texts)||d.texts.length!==row.fragments.length||Object.hasOwn(d,'text')||Object.hasOwn(d,'fragmentIndex'))fail('INVALID_SPLIT_DECISION');d.texts.forEach(validateText);}else if(d.action==='continuous'){if(row.fragments.length<2||Object.hasOwn(d,'texts')||Object.hasOwn(d,'fragmentIndex'))fail('INVALID_CONTINUOUS_DECISION');validateText(d.text);}else fail('INVALID_DECISION_ACTION');}return bundle;}
export function resolve(plan,bundle){validateDecisions(plan,bundle);const cues=[],receipt=[],unresolved=[];for(const row of plan.rows){const d=bundle.decisions[row.id];const record={cueId:row.id,sourceNumber:row.sourceNumber,sourceInterval:{startMs:row.startMs,endMs:row.endMs},originalText:row.text,status:row.status,reasons:row.reasons,fragments:row.fragments,decision:d||null,outputNumbers:[]};let selected=[];if(row.status==='review'&&!d)unresolved.push(row.id);else if(row.status==='automatic')selected=row.fragments.map(f=>({fragments:[f],text:row.text}));else if(d?.action==='fragment')selected=[{fragments:[row.fragments[d.fragmentIndex]],text:validateText(d.text)}];else if(d?.action==='split')selected=row.fragments.map((f,i)=>({fragments:[f],text:validateText(d.texts[i])}));else if(d?.action==='continuous')selected=[{fragments:row.fragments,text:validateText(d.text)}];for(const s of selected){const f=s.fragments;const out={number:cues.length+1,startMs:f[0].outputStartMs,endMs:f.at(-1).outputEndMs,text:s.text,sourceCueId:row.id,sourceIntervals:f.map(x=>({startMs:x.sourceStartMs,endMs:x.sourceEndMs,rangeIndexes:x.rangeIndexes})),decision:row.status==='automatic'?'automatic':d.action};if(out.startMs>=out.endMs||out.endMs>plan.durationMs||(cues.at(-1)?.endMs||0)>out.startMs)fail('INVALID_OUTPUT_INTERVAL');record.outputNumbers.push(out.number);cues.push(out);}receipt.push(record);}return {cues,receipt,unresolved,durationMs:plan.durationMs};}
const csvCell=value=>{let s=typeof value==='string'?value:JSON.stringify(value);if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
export function exportBundle(plan,bundle){const result=resolve(plan,bundle);if(result.unresolved.length)fail('UNRESOLVED_CUES',result.unresolved.join(', '));if(!result.cues.length)fail('EMPTY_EXPORT');const srt=result.cues.map(c=>`${c.number}\n${stamp(c.startMs)} --> ${stamp(c.endMs)}\n${c.text}\n`).join('\n');const escapeVtt=s=>s.replaceAll('&','&amp;');const vtt='WEBVTT\n\n'+result.cues.map(c=>`${c.number}\n${stamp(c.startMs,true)} --> ${stamp(c.endMs,true)}\n${escapeVtt(c.text)}\n`).join('\n');const provenance={schema:'caption-seam-provenance/v1',sourceHash:plan.sourceHash,cutMapHash:plan.cutMapHash,basisHash:plan.basisHash,cutMap:plan.map,durationMs:plan.durationMs,semantics:'half-open millisecond intervals; ascending source keeps; 1x concatenation',cues:result.cues,review:result.receipt};const cols=['cue_id','source_number','source_start_ms','source_end_ms','status','reasons','action','original_text','source_fragments','output_numbers'];const csv=cols.join(',')+'\r\n'+result.receipt.map(r=>[r.cueId,r.sourceNumber,r.sourceInterval.startMs,r.sourceInterval.endMs,r.status,r.reasons,r.decision?.action||r.status,r.originalText,r.fragments,r.outputNumbers].map(csvCell).join(',')).join('\r\n')+'\r\n';return {srt,vtt,decisions:JSON.stringify(bundle,null,2)+'\n',provenance:JSON.stringify(provenance,null,2)+'\n',csv,result};}
